services:
  waha:
    image: devlikeapro/waha:latest
    container_name: vision-waha
    restart: always
    env_file:
      - ./waha/.env
    environment:
      - WAHA_WEBHOOK_URL=http://n8n:5679/webhook/whatsapp
      - WAHA_MULTI_DEVICE=true
    volumes:
      - ./waha/data:/app/data
    ports:
      - "3000:3000"

  webhook:
    build: ./webhook
    container_name: vision-webhook
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./webhook:/app

  n8n:
    image: n8nio/n8n:latest
    container_name: vision-n8n
    restart: always
    environment:
      - N8N_HOST=n8n.local
      - N8N_PORT=5679
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n:5679/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_EDITOR_BASE_URL=http://localhost:5679
    ports:
      - "5679:5679"
    volumes:
      - ./n8n:/home/node/.n8n
